// Comprehensive dummy data for UNI360 Master Admin Portal

export const MOCK_USERS = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@email.com",
    role: "agent",
    status: "active",
    country: "UK",
    uuid: "AGT-2024-001",
    createdAt: "2024-01-15",
    lastLogin: "2024-08-26",
    phone: "+44 7700 900123",
    avatar:
      "https://ui-avatars.com/api/?name=John+Smith&background=3b82f6&color=fff",
    performance: {
      totalApplications: 45,
      successfulPlacements: 32,
      revenue: 12000,
      rating: 4.8,
    },
  },
  {
    id: 2,
    name: "Sarah Wilson",
    email: "sarah.wilson@email.com",
    role: "student",
    status: "active",
    country: "UK",
    uuid: "STU-2024-001",
    createdAt: "2024-02-10",
    lastLogin: "2024-08-25",
    phone: "+44 7700 900124",
    avatar:
      "https://ui-avatars.com/api/?name=Sarah+Wilson&background=10b981&color=fff",
    course: "Computer Science",
    university: "University of Oxford",
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike.johnson@email.com",
    role: "admin",
    status: "active",
    country: "Germany",
    uuid: "ADM-2024-001",
    createdAt: "2024-01-20",
    lastLogin: "2024-08-26",
    phone: "+49 30 12345678",
    avatar:
      "https://ui-avatars.com/api/?name=Mike+Johnson&background=8b5cf6&color=fff",
    permissions: ["user_management", "university_management", "reports"],
  },
  {
    id: 4,
    name: "Emma Thompson",
    email: "emma.thompson@email.com",
    role: "student",
    status: "active",
    country: "UK",
    uuid: "STU-2024-002",
    createdAt: "2024-03-05",
    lastLogin: "2024-08-24",
    phone: "+44 7700 900125",
    avatar:
      "https://ui-avatars.com/api/?name=Emma+Thompson&background=f59e0b&color=fff",
    course: "Engineering",
    university: "University of Cambridge",
  },
  {
    id: 5,
    name: "Hans Mueller",
    email: "hans.mueller@email.com",
    role: "agent",
    status: "active",
    country: "Germany",
    uuid: "AGT-2024-002",
    createdAt: "2024-01-25",
    lastLogin: "2024-08-26",
    phone: "+49 30 12345679",
    avatar:
      "https://ui-avatars.com/api/?name=Hans+Mueller&background=ef4444&color=fff",
    performance: {
      totalApplications: 35,
      successfulPlacements: 25,
      revenue: 9500,
      rating: 4.6,
    },
  },
  {
    id: 6,
    name: "Lisa Anderson",
    email: "lisa.anderson@email.com",
    role: "sub_agent",
    status: "inactive",
    country: "UK",
    uuid: "SAG-2024-001",
    createdAt: "2024-02-15",
    lastLogin: "2024-08-20",
    phone: "+44 7700 900126",
    avatar:
      "https://ui-avatars.com/api/?name=Lisa+Anderson&background=6b7280&color=fff",
    parentAgent: "John Smith",
    performance: {
      totalApplications: 12,
      successfulPlacements: 8,
      revenue: 2400,
      rating: 4.2,
    },
  },
];

export const MOCK_UNIVERSITIES = [
  {
    id: 1,
    name: "University of Oxford",
    country: "UK",
    location: "Oxford, England",
    type: "Public",
    tuitionFee: 25000,
    commissionRate: 12,
    status: "active",
    programs: 45,
    ranking: 2,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/ff/Oxford-University-Coat-Arms.svg/73px-Oxford-University-Coat-Arms.svg.png",
    establishedYear: 1096,
    totalStudents: 24000,
    internationalStudents: 8500,
    acceptanceRate: 17,
    courses: ["Computer Science", "Engineering", "Medicine", "Law", "Business"],
    facilities: [
      "Library",
      "Sports Center",
      "Research Labs",
      "Student Housing",
    ],
    contactEmail: "admissions@ox.ac.uk",
    contactPhone: "+44 1865 270000",
  },
  {
    id: 2,
    name: "University of Cambridge",
    country: "UK",
    location: "Cambridge, England",
    type: "Public",
    tuitionFee: 26000,
    commissionRate: 11,
    status: "active",
    programs: 48,
    ranking: 1,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/University_of_Cambridge_coat_of_arms_official.svg/75px-University_of_Cambridge_coat_of_arms_official.svg.png",
    establishedYear: 1209,
    totalStudents: 25000,
    internationalStudents: 9200,
    acceptanceRate: 15,
    courses: [
      "Mathematics",
      "Natural Sciences",
      "Engineering",
      "Medicine",
      "Economics",
    ],
    facilities: [
      "Historic Libraries",
      "Research Centers",
      "Sports Facilities",
      "Colleges",
    ],
    contactEmail: "admissions@cam.ac.uk",
    contactPhone: "+44 1223 337733",
  },
  {
    id: 3,
    name: "Technical University of Munich",
    country: "Germany",
    location: "Munich, Germany",
    type: "Public",
    tuitionFee: 15000,
    commissionRate: 10,
    status: "active",
    programs: 52,
    ranking: 12,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/TUM-Logo.svg/75px-TUM-Logo.svg.png",
    establishedYear: 1868,
    totalStudents: 45000,
    internationalStudents: 12000,
    acceptanceRate: 25,
    courses: [
      "Engineering",
      "Computer Science",
      "Physics",
      "Architecture",
      "Management",
    ],
    facilities: [
      "Modern Labs",
      "Innovation Center",
      "Sports Complex",
      "Student Services",
    ],
    contactEmail: "admissions@tum.de",
    contactPhone: "+49 89 289 01",
  },
  {
    id: 4,
    name: "Imperial College London",
    country: "UK",
    location: "London, England",
    type: "Public",
    tuitionFee: 28000,
    commissionRate: 13,
    status: "active",
    programs: 35,
    ranking: 8,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Imperial_College_London_crest.svg/75px-Imperial_College_London_crest.svg.png",
    establishedYear: 1907,
    totalStudents: 17000,
    internationalStudents: 7500,
    acceptanceRate: 20,
    courses: ["Engineering", "Medicine", "Natural Sciences", "Business"],
    facilities: [
      "Research Labs",
      "Medical School",
      "Business School",
      "Sports Center",
    ],
    contactEmail: "admissions@imperial.ac.uk",
    contactPhone: "+44 20 7589 5111",
  },
  {
    id: 5,
    name: "Heidelberg University",
    country: "Germany",
    location: "Heidelberg, Germany",
    type: "Public",
    tuitionFee: 12000,
    commissionRate: 9,
    status: "active",
    programs: 38,
    ranking: 15,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Heidelberg_University_seal.svg/75px-Heidelberg_University_seal.svg.png",
    establishedYear: 1386,
    totalStudents: 30000,
    internationalStudents: 6000,
    acceptanceRate: 30,
    courses: ["Medicine", "Law", "Philosophy", "Natural Sciences", "Economics"],
    facilities: [
      "Historic Campus",
      "Medical Center",
      "Research Institute",
      "Library",
    ],
    contactEmail: "admissions@uni-heidelberg.de",
    contactPhone: "+49 6221 54 0",
  },
];

export const MOCK_APPLICATIONS = [
  {
    id: 1,
    applicationId: "APP-2024-001",
    studentName: "Emma Thompson",
    studentId: "STU-2024-002",
    studentEmail: "emma.thompson@email.com",
    universityName: "University of Oxford",
    universityId: 1,
    agentName: "John Smith",
    agentId: 1,
    status: "submitted",
    submittedDate: "2024-08-15",
    lastUpdated: "2024-08-20",
    program: "Computer Science",
    country: "UK",
    documents: ["SOP", "LOR", "Transcript", "Passport"],
    fees: {
      applicationFee: 500,
      tuitionFee: 25000,
      status: "paid",
    },
    timeline: [
      {
        date: "2024-08-15",
        status: "submitted",
        note: "Application submitted successfully",
      },
      {
        date: "2024-08-18",
        status: "under_review",
        note: "Application under university review",
      },
      {
        date: "2024-08-20",
        status: "documents_requested",
        note: "Additional documents requested",
      },
    ],
  },
  {
    id: 2,
    applicationId: "APP-2024-002",
    studentName: "James Wilson",
    studentId: "STU-2024-003",
    studentEmail: "james.wilson@email.com",
    universityName: "University of Cambridge",
    universityId: 2,
    agentName: "Sarah Wilson",
    agentId: 2,
    status: "offer_received",
    submittedDate: "2024-08-10",
    lastUpdated: "2024-08-25",
    program: "Engineering",
    country: "UK",
    documents: ["SOP", "LOR", "Transcript", "Passport", "IELTS"],
    fees: {
      applicationFee: 500,
      tuitionFee: 26000,
      status: "paid",
    },
    timeline: [
      {
        date: "2024-08-10",
        status: "submitted",
        note: "Application submitted",
      },
      { date: "2024-08-15", status: "under_review", note: "Under review" },
      {
        date: "2024-08-22",
        status: "interview_scheduled",
        note: "Interview scheduled",
      },
      {
        date: "2024-08-25",
        status: "offer_received",
        note: "Conditional offer received",
      },
    ],
  },
  {
    id: 3,
    applicationId: "APP-2024-003",
    studentName: "Maria Garcia",
    studentId: "STU-2024-004",
    studentEmail: "maria.garcia@email.com",
    universityName: "Technical University of Munich",
    universityId: 3,
    agentName: "Hans Mueller",
    agentId: 5,
    status: "admitted",
    submittedDate: "2024-07-20",
    lastUpdated: "2024-08-26",
    program: "Computer Science",
    country: "Germany",
    documents: ["SOP", "LOR", "Transcript", "Passport", "German Proficiency"],
    fees: {
      applicationFee: 300,
      tuitionFee: 15000,
      status: "paid",
    },
    timeline: [
      {
        date: "2024-07-20",
        status: "submitted",
        note: "Application submitted",
      },
      { date: "2024-07-25", status: "under_review", note: "Under review" },
      {
        date: "2024-08-10",
        status: "interview_completed",
        note: "Interview completed successfully",
      },
      { date: "2024-08-20", status: "offer_received", note: "Offer received" },
      { date: "2024-08-26", status: "admitted", note: "Admission confirmed" },
    ],
  },
];

export const MOCK_COMMISSIONS = [
  {
    id: 1,
    universityName: "University of Oxford",
    universityId: 1,
    agentName: "John Smith",
    agentId: 1,
    studentName: "Emma Thompson",
    studentId: "STU-2024-002",
    applicationId: "APP-2024-001",
    amount: 3000,
    rate: 12,
    tuitionFee: 25000,
    status: "pending",
    createdDate: "2024-08-15",
    dueDate: "2024-09-15",
    invoiceNumber: "INV-2024-001",
    description: "Commission for Computer Science application placement",
  },
  {
    id: 2,
    universityName: "University of Cambridge",
    universityId: 2,
    agentName: "Sarah Wilson",
    agentId: 2,
    studentName: "James Wilson",
    studentId: "STU-2024-003",
    applicationId: "APP-2024-002",
    amount: 2860,
    rate: 11,
    tuitionFee: 26000,
    status: "paid",
    createdDate: "2024-08-10",
    paidDate: "2024-08-25",
    invoiceNumber: "INV-2024-002",
    description: "Commission for Engineering application placement",
  },
  {
    id: 3,
    universityName: "Technical University of Munich",
    universityId: 3,
    agentName: "Hans Mueller",
    agentId: 5,
    studentName: "Maria Garcia",
    studentId: "STU-2024-004",
    applicationId: "APP-2024-003",
    amount: 1500,
    rate: 10,
    tuitionFee: 15000,
    status: "processing",
    createdDate: "2024-08-20",
    dueDate: "2024-09-20",
    invoiceNumber: "INV-2024-003",
    description: "Commission for Computer Science application placement",
  },
];

export const MOCK_PAYMENTS = [
  {
    id: 1,
    transactionId: "TXN-2024-001",
    studentName: "Emma Thompson",
    studentId: "STU-2024-002",
    amount: 500,
    currency: "GBP",
    type: "application_fee",
    status: "completed",
    description: "Application fee for Oxford University",
    createdDate: "2024-08-15",
    completedDate: "2024-08-15",
    paymentMethod: "Credit Card",
    reference: "REF-001-2024",
  },
  {
    id: 2,
    transactionId: "TXN-2024-002",
    studentName: "James Wilson",
    studentId: "STU-2024-003",
    amount: 25000,
    currency: "GBP",
    type: "tuition",
    status: "pending",
    description: "First semester tuition payment - Cambridge",
    createdDate: "2024-08-20",
    paymentMethod: "Bank Transfer",
    reference: "REF-002-2024",
  },
  {
    id: 3,
    transactionId: "TXN-2024-003",
    studentName: "Maria Garcia",
    studentId: "STU-2024-004",
    amount: 200,
    currency: "EUR",
    type: "service_fee",
    status: "completed",
    description: "Administrative service fee",
    createdDate: "2024-08-18",
    completedDate: "2024-08-18",
    paymentMethod: "PayPal",
    reference: "REF-003-2024",
  },
  {
    id: 4,
    transactionId: "TXN-2024-004",
    studentName: "Sarah Wilson",
    studentId: "STU-2024-001",
    amount: 150,
    currency: "GBP",
    type: "document_verification",
    status: "failed",
    description: "Document verification fee",
    createdDate: "2024-08-22",
    failedDate: "2024-08-22",
    paymentMethod: "Credit Card",
    reference: "REF-004-2024",
    failureReason: "Insufficient funds",
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: 1,
    fileName: "SOP_Emma_Thompson.pdf",
    studentName: "Emma Thompson",
    studentId: "STU-2024-002",
    type: "SOP",
    uploadDate: "2024-08-14",
    status: "approved",
    size: "2.3 MB",
    applicationId: "APP-2024-001",
    verifiedBy: "AI Validator",
    verificationDate: "2024-08-15",
    downloadUrl: "#",
  },
  {
    id: 2,
    fileName: "Transcript_James_Wilson.pdf",
    studentName: "James Wilson",
    studentId: "STU-2024-003",
    type: "Transcript",
    uploadDate: "2024-08-09",
    status: "pending_review",
    size: "1.8 MB",
    applicationId: "APP-2024-002",
    downloadUrl: "#",
  },
  {
    id: 3,
    fileName: "Passport_Maria_Garcia.pdf",
    studentName: "Maria Garcia",
    studentId: "STU-2024-004",
    type: "Passport",
    uploadDate: "2024-07-19",
    status: "approved",
    size: "1.2 MB",
    applicationId: "APP-2024-003",
    verifiedBy: "Manual Review",
    verificationDate: "2024-07-20",
    downloadUrl: "#",
  },
  {
    id: 4,
    fileName: "LOR_Emma_Thompson_1.pdf",
    studentName: "Emma Thompson",
    studentId: "STU-2024-002",
    type: "LOR",
    uploadDate: "2024-08-14",
    status: "rejected",
    size: "1.5 MB",
    applicationId: "APP-2024-001",
    rejectionReason: "Format not acceptable",
    downloadUrl: "#",
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 1,
    message:
      "New application submitted for University of Oxford - Computer Science",
    time: "2 hours ago",
    read: false,
    type: "application",
    priority: "high",
    actionUrl: "/applications/1",
  },
  {
    id: 2,
    message: "Payment of £2,500 received from student Emma Thompson",
    time: "4 hours ago",
    read: false,
    type: "payment",
    priority: "medium",
    actionUrl: "/payments/1",
  },
  {
    id: 3,
    message: "Commission payment processed for University of Cambridge",
    time: "1 day ago",
    read: true,
    type: "commission",
    priority: "low",
    actionUrl: "/commissions/2",
  },
  {
    id: 4,
    message: "Document verification completed for Maria Garcia",
    time: "2 days ago",
    read: true,
    type: "document",
    priority: "medium",
    actionUrl: "/documents/3",
  },
  {
    id: 5,
    message: "New agent registration: Lisa Anderson",
    time: "3 days ago",
    read: true,
    type: "user",
    priority: "medium",
    actionUrl: "/users/6",
  },
];

export const MOCK_REPORTS = {
  conversionRates: {
    monthly: [
      { month: "Jan", applications: 45, admissions: 32, rate: 71 },
      { month: "Feb", applications: 52, admissions: 38, rate: 73 },
      { month: "Mar", applications: 48, admissions: 35, rate: 73 },
      { month: "Apr", applications: 60, admissions: 42, rate: 70 },
      { month: "May", applications: 55, admissions: 41, rate: 75 },
      { month: "Jun", applications: 58, admissions: 45, rate: 78 },
      { month: "Jul", applications: 62, admissions: 48, rate: 77 },
      { month: "Aug", applications: 67, admissions: 52, rate: 78 },
    ],
  },
  revenueAnalysis: {
    byCountry: [
      { country: "UK", revenue: 125000, percentage: 65 },
      { country: "Germany", revenue: 68000, percentage: 35 },
    ],
    byUniversity: [
      { university: "University of Oxford", revenue: 45000, applications: 18 },
      {
        university: "University of Cambridge",
        revenue: 42000,
        applications: 16,
      },
      {
        university: "Imperial College London",
        revenue: 38000,
        applications: 14,
      },
      {
        university: "Technical University of Munich",
        revenue: 35000,
        applications: 20,
      },
      { university: "Heidelberg University", revenue: 33000, applications: 18 },
    ],
  },
  studentDistribution: {
    byProgram: [
      { program: "Computer Science", count: 45, percentage: 35 },
      { program: "Engineering", count: 38, percentage: 30 },
      { program: "Business", count: 25, percentage: 20 },
      { program: "Medicine", count: 12, percentage: 9 },
      { program: "Law", count: 8, percentage: 6 },
    ],
    byCountry: [
      { country: "India", count: 45, percentage: 35 },
      { country: "China", count: 32, percentage: 25 },
      { country: "Nigeria", count: 28, percentage: 22 },
      { country: "Pakistan", count: 15, percentage: 12 },
      { country: "Bangladesh", count: 8, percentage: 6 },
    ],
  },
};

export const MOCK_AI_TOOLS = {
  sopGenerator: {
    templates: [
      "Computer Science",
      "Engineering",
      "Business",
      "Medicine",
      "Liberal Arts",
    ],
    recentGenerations: [
      {
        id: 1,
        studentName: "Emma Thompson",
        program: "Computer Science",
        university: "University of Oxford",
        generatedDate: "2024-08-14",
        wordCount: 850,
        status: "approved",
      },
      {
        id: 2,
        studentName: "James Wilson",
        program: "Engineering",
        university: "University of Cambridge",
        generatedDate: "2024-08-12",
        wordCount: 920,
        status: "pending_review",
      },
    ],
  },
  apsGenerator: {
    recentGenerations: [
      {
        id: 1,
        studentName: "Maria Garcia",
        program: "Computer Science",
        university: "Technical University of Munich",
        generatedDate: "2024-08-10",
        status: "completed",
      },
    ],
  },
  chatbotLogs: [
    {
      id: 1,
      studentName: "Emma Thompson",
      query: "What documents do I need for Oxford application?",
      response:
        "For Oxford University applications, you need: SOP, LOR, Transcripts, Passport, IELTS...",
      timestamp: "2024-08-26 10:30:00",
      resolved: true,
      category: "documentation",
    },
    {
      id: 2,
      studentName: "James Wilson",
      query: "When is the application deadline for Cambridge?",
      response:
        "The application deadline for Cambridge University is October 15th for the next academic year...",
      timestamp: "2024-08-26 09:15:00",
      resolved: true,
      category: "deadlines",
    },
    {
      id: 3,
      studentName: "Anonymous",
      query: "How much is the tuition fee for engineering programs?",
      response:
        "Tuition fees vary by university. For UK universities, engineering programs typically cost...",
      timestamp: "2024-08-26 08:45:00",
      resolved: false,
      category: "fees",
    },
  ],
};

// Admin Registration Requests Mock Data
export const MOCK_ADMIN_REQUESTS = [
  {
    id: "REQ-2024-001",
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@education.uk",
    phone: "+44 7700 900567",
    organization: "UK Education Consultancy",
    position: "Senior Education Consultant",
    experience: "8 years",
    status: "pending",
    submittedAt: "2024-09-08T10:30:00Z",
    documents: [
      {
        type: "cv",
        name: "David_Brown_CV.pdf",
        url: "/documents/cv/david_brown_cv.pdf",
      },
      {
        type: "qualification",
        name: "Certifications.pdf",
        url: "/documents/qualifications/david_brown_cert.pdf",
      },
    ],
    bio: "Experienced education consultant with expertise in UK university admissions. Worked with over 500 students in the past 8 years.",
    specialization: "UK Universities",
    languages: ["English", "German"],
    preferredRole: "Senior Consultant",
    availability: "Full-time",
    expectedSalary: "£45,000 - £55,000",
  },
  {
    id: "REQ-2024-002",
    firstName: "Maria",
    lastName: "Rodriguez",
    email: "maria.rodriguez@globalacademy.es",
    phone: "+34 612 345 678",
    organization: "Global Academy Spain",
    position: "Academic Director",
    experience: "12 years",
    status: "pending",
    submittedAt: "2024-09-07T14:20:00Z",
    documents: [
      {
        type: "cv",
        name: "Maria_Rodriguez_CV.pdf",
        url: "/documents/cv/maria_rodriguez_cv.pdf",
      },
      {
        type: "business_license",
        name: "Business_License.pdf",
        url: "/documents/licenses/global_academy_license.pdf",
      },
    ],
    bio: "Academic director with extensive experience in international student placements. Currently managing a team of 15 consultants.",
    specialization: "European Universities",
    languages: ["Spanish", "English", "French"],
    region: "Spain & Portugal",
    businessModel: "Commission-based partnership",
    currentStudents: "200+ active students",
  },
  {
    id: "REQ-2024-003",
    firstName: "Robert",
    lastName: "Chen",
    email: "robert.chen@asiaedu.sg",
    phone: "+65 9123 4567",
    organization: "Asia Education Hub",
    position: "Founder & CEO",
    experience: "15 years",
    requestType: "external_admin",
    status: "approved",
    adminType: "external_admin",
    submittedAt: "2024-09-05T09:15:00Z",
    approvedAt: "2024-09-06T16:30:00Z",
    approvedBy: "Master Admin",
    documents: [
      {
        type: "cv",
        name: "Robert_Chen_CV.pdf",
        url: "/documents/cv/robert_chen_cv.pdf",
      },
      {
        type: "business_license",
        name: "Company_Registration.pdf",
        url: "/documents/licenses/asia_edu_registration.pdf",
      },
    ],
    bio: "Founder of Asia Education Hub with 15 years of experience in international education. Successfully placed over 1000 students worldwide.",
    specialization: "Asian & UK Universities",
    languages: ["English", "Mandarin", "Cantonese"],
    region: "Southeast Asia",
    businessModel: "Full-service education consultancy",
    currentStudents: "500+ active students",
  },
  {
    id: "REQ-2024-004",
    firstName: "Emily",
    lastName: "Thompson",
    email: "emily.thompson@studyabroad.ca",
    phone: "+1 416 555 0123",
    organization: "Study Abroad Canada",
    position: "Senior Advisor",
    experience: "6 years",
    requestType: "team_member",
    status: "declined",
    submittedAt: "2024-09-03T11:45:00Z",
    declinedAt: "2024-09-04T13:20:00Z",
    declinedBy: "Master Admin",
    declineReason:
      "Insufficient experience in UK university systems. Recommend reapplying after gaining more specific UK education experience.",
    documents: [
      {
        type: "cv",
        name: "Emily_Thompson_CV.pdf",
        url: "/documents/cv/emily_thompson_cv.pdf",
      },
    ],
    bio: "Education advisor specializing in North American university admissions. Looking to expand expertise to UK universities.",
    specialization: "North American Universities",
    languages: ["English", "French"],
    preferredRole: "Education Consultant",
    availability: "Part-time",
    expectedSalary: "£35,000 - £40,000",
  },
  {
    id: "REQ-2024-005",
    firstName: "Ahmed",
    lastName: "Al-Rashid",
    email: "ahmed.alrashid@middleeastedu.ae",
    phone: "+971 50 123 4567",
    organization: "Middle East Education Services",
    position: "Regional Manager",
    experience: "10 years",
    status: "pending",
    submittedAt: "2024-09-06T16:00:00Z",
    documents: [
      {
        type: "cv",
        name: "Ahmed_AlRashid_CV.pdf",
        url: "/documents/cv/ahmed_alrashid_cv.pdf",
      },
      {
        type: "business_license",
        name: "UAE_Business_License.pdf",
        url: "/documents/licenses/mees_license.pdf",
      },
    ],
    bio: "Regional manager with extensive experience in MENA region student placements. Strong network with UK universities.",
    specialization: "UK & European Universities",
    languages: ["Arabic", "English"],
    region: "Middle East & North Africa",
    businessModel: "Regional partnership network",
    currentStudents: "300+ active students",
  },
  {
    id: "REQ-2024-006",
    firstName: "Lisa",
    lastName: "Kumar",
    email: "lisa.kumar@brightfuture.in",
    phone: "+91 98765 43210",
    organization: "Bright Future Consultancy",
    position: "Senior Consultant",
    experience: "7 years",
    requestType: "team_member",
    status: "approved",
    adminType: "team_member",
    submittedAt: "2024-09-01T08:30:00Z",
    approvedAt: "2024-09-02T10:15:00Z",
    approvedBy: "Master Admin",
    documents: [
      {
        type: "cv",
        name: "Lisa_Kumar_CV.pdf",
        url: "/documents/cv/lisa_kumar_cv.pdf",
      },
      {
        type: "qualification",
        name: "ICEF_Certification.pdf",
        url: "/documents/qualifications/lisa_kumar_icef.pdf",
      },
    ],
    bio: "ICEF certified consultant with strong track record in UK university placements. Specialized in STEM programs.",
    specialization: "STEM Programs",
    languages: ["English", "Hindi", "Tamil"],
    preferredRole: "Senior Consultant",
    availability: "Full-time",
    expectedSalary: "£40,000 - £50,000",
  },
];
